language: node_js
node_js:
- 0.12.7
branches:
  only:
  - master
before_install: npm install -g grunt-cli
before_script:
- npm install -g bower
- npm install -g grunt
- bower install
deploy:
  provider: heroku
  api_key:
    - secure: XKPWm+6TjgF23qjP90qYN0B7wIFn6wUdD8a38SXAtTc+LQYCJVt/Mbo3m0YpWKZAwwpNqc40C8/dklU9YHVy6Gaob4AHbtla+J6klOAjAdSdBN33zDeYLfbRo00YnM6uebn22nUCbWSciRawEn5jTPA+UWNv3tNNbjnajvcMWz144cSWVo3xKk8/ZxxJwstPEk5G5AXFBePoAopd8Rs/dKMw1DXvfTy4p63tuduQt0BpWnO2XtzYGQ0keNiy6NVnLIAuwSOy8bLDLRsUt5TiIVbit7OqN11SD3zkIglnCk5p/j7Bg89FIfqo7mOrRnZiyr0c7LvxvwOgXUSYxFJQNR0ORctLmYddN4M7ceZZlAbwZMY9e8Xn2U63SIH+Vh0sqe8IsYOyl6/etdlNrfFyom7P3tPcapbD0U3MF5V6O1KIhPnkLSs1VeRM25dFOMGxuAaXVg+qt6aJvvAZtIF2wmEoy/JuugCQnsZQPKdJQesgS+ZXRdsUlm9VpabWTc+XoYnlBF/mGHDFzY8cYygc2mJlPXMZwnbH45zPExrbjbF6Rw9sECx8uxg7Pa5eDDI7vldQt67QS8IKLHUpDaiwg6x4WWO+5tLp8uSjI+VcfQVAutNRMKhaAtwhZ+XWZnOVEFTibSlu7bJtkXN1qloH1oSG9XYyBzGI0Vt1eg7sw04=
  app: ohno
