var natural = require('natural');
var tokenizer = new natural.WordTokenizer();
var metaphone = natural.Metaphone;
var soundEx = natural.SoundEx;
var wikiHelper = require('./wikiHelper');
var http = require('http');
var https = require('https');

// list of common bad words and their myriad of spellings
// curated from Google's list of common bad words
var badWords = {
    "4r5e": true,
    "5h1t": true,
    "5hit": true,
    "a55": true,
    "anal": true,
    "anus": true,
    "ar5e": true,
    "arrse": true,
    "arse": true,
    "ass": true,
    "ass-fucker": true,
    "asses": true,
    "assfucker": true,
    "assfukka": true,
    "asshole": true,
    "assholes": true,
    "asswhole": true,
    "a_s_s": true,
    "b!tch": true,
    "b00bs": true,
    "b17ch": true,
    "b1tch": true,
    "ballbag": true,
    "balls": true,
    "ballsack": true,
    "bastard": true,
    "beastial": true,
    "beastiality": true,
    "bellend": true,
    "bestial": true,
    "bestiality": true,
    "bi+ch": true,
    "biatch": true,
    "bitch": true,
    "bitcher": true,
    "bitchers": true,
    "bitches": true,
    "bitchin": true,
    "bitching": true,
    "bloody": true,
    "blow job": true,
    "blowjob": true,
    "blowjobs": true,
    "boiolas": true,
    "bollock": true,
    "bollok": true,
    "boner": true,
    "boob": true,
    "boobs": true,
    "booobs": true,
    "boooobs": true,
    "booooobs": true,
    "booooooobs": true,
    "breasts": true,
    "buceta": true,
    "bugger": true,
    "bum": true,
    "bunny fucker": true,
    "butt": true,
    "butthole": true,
    "buttmuch": true,
    "buttplug": true,
    "c0ck": true,
    "c0cksucker": true,
    "carpet muncher": true,
    "cawk": true,
    "chink": true,
    "cipa": true,
    "cl1t": true,
    "clit": true,
    "clitoris": true,
    "clits": true,
    "cnut": true,
    "cock": true,
    "cock-sucker": true,
    "cockface": true,
    "cockhead": true,
    "cockmunch": true,
    "cockmuncher": true,
    "cocks": true,
    "cocksuck ": true,
    "cocksucked ": true,
    "cocksucker": true,
    "cocksucking": true,
    "cocksucks ": true,
    "cocksuka": true,
    "cocksukka": true,
    "cok": true,
    "cokmuncher": true,
    "coksucka": true,
    "coon": true,
    "cox": true,
    "crap": true,
    "cum": true,
    "cummer": true,
    "cumming": true,
    "cums": true,
    "cumshot": true,
    "cunilingus": true,
    "cunillingus": true,
    "cunnilingus": true,
    "cunt": true,
    "cuntlick ": true,
    "cuntlicker ": true,
    "cuntlicking ": true,
    "cunts": true,
    "cyalis": true,
    "cyberfuc": true,
    "cyberfuck ": true,
    "cyberfucked ": true,
    "cyberfucker": true,
    "cyberfuckers": true,
    "cyberfucking ": true,
    "d1ck": true,
    "damn": true,
    "dick": true,
    "dickhead": true,
    "dildo": true,
    "dildos": true,
    "dink": true,
    "dinks": true,
    "dirsa": true,
    "dlck": true,
    "dog-fucker": true,
    "doggin": true,
    "dogging": true,
    "donkeyribber": true,
    "doosh": true,
    "duche": true,
    "dyke": true,
    "ejaculate": true,
    "ejaculated": true,
    "ejaculates ": true,
    "ejaculating ": true,
    "ejaculatings": true,
    "ejaculation": true,
    "ejakulate": true,
    "f u c k": true,
    "f u c k e r": true,
    "f4nny": true,
    "fag": true,
    "fagging": true,
    "faggitt": true,
    "faggot": true,
    "faggs": true,
    "fagot": true,
    "fagots": true,
    "fags": true,
    "fanny": true,
    "fannyflaps": true,
    "fannyfucker": true,
    "fanyy": true,
    "fatass": true,
    "fcuk": true,
    "fcuker": true,
    "fcuking": true,
    "feck": true,
    "fecker": true,
    "felching": true,
    "fellate": true,
    "fellatio": true,
    "fingerfuck ": true,
    "fingerfucked ": true,
    "fingerfucker ": true,
    "fingerfuckers": true,
    "fingerfucking ": true,
    "fingerfucks ": true,
    "fistfuck": true,
    "fistfucked ": true,
    "fistfucker ": true,
    "fistfuckers ": true,
    "fistfucking ": true,
    "fistfuckings ": true,
    "fistfucks ": true,
    "flange": true,
    "fook": true,
    "fooker": true,
    "fuck": true,
    "fucka": true,
    "fucked": true,
    "fucker": true,
    "fuckers": true,
    "fuckhead": true,
    "fuckheads": true,
    "fuckin": true,
    "fucking": true,
    "fuckings": true,
    "fuckingshitmotherfucker": true,
    "fuckme ": true,
    "fucks": true,
    "fuckwhit": true,
    "fuckwit": true,
    "fudge packer": true,
    "fudgepacker": true,
    "fuk": true,
    "fuker": true,
    "fukker": true,
    "fukkin": true,
    "fuks": true,
    "fukwhit": true,
    "fukwit": true,
    "fux": true,
    "fux0r": true,
    "f_u_c_k": true,
    "gangbang": true,
    "gangbanged ": true,
    "gangbangs ": true,
    "gaylord": true,
    "gaysex": true,
    "goatse": true,
    "God": true,
    "god-dam": true,
    "god-damned": true,
    "goddamn": true,
    "goddamned": true,
    "hardcoresex ": true,
    "hell": true,
    "heshe": true,
    "hoar": true,
    "hoare": true,
    "hoer": true,
    "homo": true,
    "hore": true,
    "horniest": true,
    "horny": true,
    "hotsex": true,
    "jack-off ": true,
    "jackoff": true,
    "jap": true,
    "jerk-off ": true,
    "jism": true,
    "jiz ": true,
    "jizm ": true,
    "jizz": true,
    "kawk": true,
    "knob": true,
    "knobead": true,
    "knobed": true,
    "knobend": true,
    "knobhead": true,
    "knobjocky": true,
    "knobjokey": true,
    "kock": true,
    "kondum": true,
    "kondums": true,
    "kum": true,
    "kummer": true,
    "kumming": true,
    "kums": true,
    "kunilingus": true,
    "l3i+ch": true,
    "l3itch": true,
    "labia": true,
    "lmfao": true,
    "lust": true,
    "lusting": true,
    "m0f0": true,
    "m0fo": true,
    "m45terbate": true,
    "ma5terb8": true,
    "ma5terbate": true,
    "masochist": true,
    "master-bate": true,
    "masterb8": true,
    "masterbat*": true,
    "masterbat3": true,
    "masterbate": true,
    "masterbation": true,
    "masterbations": true,
    "masturbate": true,
    "mo-fo": true,
    "mof0": true,
    "mofo": true,
    "mothafuck": true,
    "mothafucka": true,
    "mothafuckas": true,
    "mothafuckaz": true,
    "mothafucked ": true,
    "mothafucker": true,
    "mothafuckers": true,
    "mothafuckin": true,
    "mothafucking ": true,
    "mothafuckings": true,
    "mothafucks": true,
    "mother fucker": true,
    "motherfuck": true,
    "motherfucked": true,
    "motherfucker": true,
    "motherfuckers": true,
    "motherfuckin": true,
    "motherfucking": true,
    "motherfuckings": true,
    "motherfuckka": true,
    "motherfucks": true,
    "muff": true,
    "mutha": true,
    "muthafecker": true,
    "muthafuckker": true,
    "muther": true,
    "mutherfucker": true,
    "n1gga": true,
    "n1gger": true,
    "nazi": true,
    "nigg3r": true,
    "nigg4h": true,
    "nigga": true,
    "niggah": true,
    "niggas": true,
    "niggaz": true,
    "nigger": true,
    "niggers ": true,
    "nob": true,
    "nob jokey": true,
    "nobhead": true,
    "nobjocky": true,
    "nobjokey": true,
    "numbnuts": true,
    "nutsack": true,
    "orgasim ": true,
    "orgasims ": true,
    "orgasm": true,
    "orgasms ": true,
    "p0rn": true,
    "pawn": true,
    "pecker": true,
    "penis": true,
    "penisfucker": true,
    "phonesex": true,
    "phuck": true,
    "phuk": true,
    "phuked": true,
    "phuking": true,
    "phukked": true,
    "phukking": true,
    "phuks": true,
    "phuq": true,
    "pigfucker": true,
    "pimpis": true,
    "piss": true,
    "pissed": true,
    "pisser": true,
    "pissers": true,
    "pisses ": true,
    "pissflaps": true,
    "pissin ": true,
    "pissing": true,
    "pissoff ": true,
    "poop": true,
    "porn": true,
    "porno": true,
    "pornography": true,
    "pornos": true,
    "pound": true,
    "prick": true,
    "pricks ": true,
    "pron": true,
    "pube": true,
    "pusse": true,
    "pussi": true,
    "pussies": true,
    "pussy": true,
    "pussys ": true,
    "rectum": true,
    "retard": true,
    "rimjaw": true,
    "rimming": true,
    "s hit": true,
    "s.o.b.": true,
    "sadist": true,
    "schlong": true,
    "screwing": true,
    "scroat": true,
    "scrote": true,
    "scrotum": true,
    "semen": true,
    "sex": true,
    "sh!+": true,
    "sh!t": true,
    "sh1t": true,
    "shag": true,
    "shagger": true,
    "shaggin": true,
    "shagging": true,
    "shemale": true,
    "shi+": true,
    "shit": true,
    "shitdick": true,
    "shite": true,
    "shited": true,
    "shitey": true,
    "shitfuck": true,
    "shitfull": true,
    "shithead": true,
    "shiting": true,
    "shitings": true,
    "shits": true,
    "shitted": true,
    "shitter": true,
    "shitters ": true,
    "shitting": true,
    "shittings": true,
    "shitty ": true,
    "skank": true,
    "slut": true,
    "sluts": true,
    "smegma": true,
    "smut": true,
    "snatch": true,
    "son-of-a-bitch": true,
    "spac": true,
    "spunk": true,
    "s_h_i_t": true,
    "t1tt1e5": true,
    "t1tties": true,
    "teets": true,
    "teez": true,
    "testical": true,
    "testicle": true,
    "tit": true,
    "titfuck": true,
    "tits": true,
    "titt": true,
    "tittie5": true,
    "tittiefucker": true,
    "titties": true,
    "tittyfuck": true,
    "tittywank": true,
    "titwank": true,
    "tosser": true,
    "turd": true,
    "tw4t": true,
    "twat": true,
    "twathead": true,
    "twatty": true,
    "twunt": true,
    "twunter": true,
    "v14gra": true,
    "v1gra": true,
    "vagina": true,
    "viagra": true,
    "vulva": true,
    "w00se": true,
    "wang": true,
    "wank": true,
    "wanker": true,
    "wanky": true,
    "whoar": true,
    "whore": true,
    "willies": true,
    "willy": true,
    "xrated": true,
    "xx1": true
};

var opponentProfile = {};

var badWordsArr = Object.keys(badWords);

var determineMessageType = function (message, avatar) {
  var obj = {};
  obj.avatar = avatar;
  obj.callback = function (data) {
    var option = {};

    var message = "you shit fuck cocksuker";

    var messageToken = tokenizer.tokenize(message);

    var curseWordCount = 0;
    var profileWordCount = 0;

    var profileWordHash = {};
    $.each(data, function (elem) {
      $.each(elem, function (subElem) {
        subElem.text.split(' ').forEach( function (word) {
          if (!(word in commonWords)) {
            profileWordHash[word] = true;
          }
        });
      });
    });

    messageToken.forEach(function (word) {
      // if the word is not in our curse words hash, check to see if the word
      // sounds like any of the words in the hash
      if ( word in badWords) {
        curseWordCount++;
      } else if ( word in profileWordHash) {
        profileWordCount++;
      } else {
        for ( var i = 0; i < badWordsArr; i++) {
          if ( metaphone.compare(word, badWordsArr[i])) {
            curseWordCount++;
            break;
          }
        }
      }
    });

    var answer = [];

    // adding a trailing 0 in the 10nth's decimal place on each number so the division will return a float
    if ( (curseWordCount).toFixed(1) / (messageToken.length).toFixed(1) > 0.3) {
      answer.push("PottyMouth");
    }

    // adding a trailing 0 in the 10nth's decimal place on each number so the division will return a float
    if ( (profileWordCount).toFixed(1) / (messageToken.length).toFixed(1) > 0.3) {
      answer.push("ProfileTroll");
    }

    return answer;
  };

  wikiHelper.scrapeWiki(obj);
};

module.exports.determineMessageType = determineMessageType;